version: "3.8"

services:
  furiax-api:
    container_name: furiax-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/app
    depends_on:
      - furiax-db
    networks:
      - furiax-network

  furiax-db:
    container_name: furiax-db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    env_file:
      - .env.dev
    networks:
      - furiax-network
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@furiax-db:27017/?authSource=admin  
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}  
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}  
    env_file:
      - .env
    depends_on:
      - furiax-db
    networks:
      - furiax-network

  # flowise:
  #   container_name: furiax-flowise
  #   image: flowiseai/flowise:2.2.7
  #   ports:
  #     - 3010:3000
  #   environment:
  #     - FLOWISE_USERNAME=${FLOWISE_USERNAME}
  #     - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
  #   networks:
  #     - furiax-network

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - TZ=America/Sao_Paulo
    restart: unless-stopped
    networks:
      - furiax-network

  furiax-xmodule:
    container_name: furiax-xmodule
    build: 
      context: ./FURIAX-Xmodule
      dockerfile: Dockerfile
    volumes:
      - ./FURIAX-Xmodule:/app
    ports:
      - 8000:8000
    depends_on:
      - furiax-api
      - furiax-db
    env_file:
      - .env
    networks:
      - furiax-network

  # furiax-document-validation:
  #   container_name: furiax-document-validation
  #   build:
  #     context: ./document-validation
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8002:8002
  #   volumes:
  #     - ./document-validation:/app

volumes:
  n8n_data:
  mongo-data:

networks:
  furiax-network:
    driver: bridge
